services:
  - type: web
    name: my-api
    env: docker
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: npm start
    envVars:
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /ms-playwright
